# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlixSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlixSwift
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'iTunesSearchAPI'
  pod 'ComplimentaryGradientView'
  target 'FlixSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
